"use client";
import { useEffect, useRef, useState } from 'react';
import defaults from '@/content/schema-template.json';
import fields from '@/content/fields.json';
import { assetPath } from '@/lib/paths';
import { validateContent } from '@/cms/schema.mjs';
type Data = Record<string,any>;
type Media = {path:string;url:string;size?:number;width?:number;height?:number;base64?:string};
const sections:Record<string,string>={site:'مشخصات و ارتباطات',works:'نمونه‌کارها',media:'کتابخانهٔ تصاویر',services:'خدمات',courses:'آموزش',plans:'پلن‌های تعرفه',pricingCategories:'دسته‌های تعرفه',categories:'دسته‌های گالری',faqs:'پرسش‌ها و دستیار',testimonials:'نظرات واقعی',processSteps:'فرایند همکاری',nav:'منوی سایت',copy:'متن همهٔ صفحات',links:'لینک‌های صفحه‌ها'};
const labels:Record<string,string>={name:'نام',title:'عنوان',age:'سن',phone:'شماره تماس',phoneLabel:'شمارهٔ نمایشی',instagram:'لینک اینستاگرام',instagramHandle:'شناسهٔ اینستاگرام',whatsapp:'لینک واتس‌اپ',whatsappMessage:'پیام پیش‌فرض واتس‌اپ',city:'شهر',serviceArea:'محدودهٔ فعالیت',tariffPdf:'لینک PDF تعرفه‌ها',heroVideo:'ویدیوی آغاز صفحه',portrait:'تصویر معرفی',hero:'تصویر اصلی سایت',description:'توضیحات',about:'معرفی کامل',id:'شناسهٔ یکتا (لاتین)',slug:'مسیر صفحه (لاتین)',category:'دسته‌بندی',image:'تصویر',width:'عرض تصویر',height:'ارتفاع تصویر',alt:'توضیح تصویر برای دسترس‌پذیری',featured:'نمایش در آثار منتخب',video:'لینک ویدیو',before:'تصویر قبل از ادیت',after:'تصویر بعد از ادیت',icon:'آیکون',desc:'توضیح کوتاه',body:'متن کامل',note:'توضیح پلن',items:'موارد شامل‌شده',quantity:'تعداد یا مدت',edit:'سطح ادیت',delivery:'زمان تحویل',extras:'خدمات تکمیلی',level:'سطح',topics:'سرفصل‌ها',format:'نوع کلاس',mode:'شیوهٔ برگزاری',duration:'مدت',q:'سؤال',a:'پاسخ',keys:'واژه‌های مرتبط با دستیار',text:'متن',role:'عنوان شخص'};
const mediaKeys=['image','portrait','hero','before','after'];
const fieldMeta=fields as Record<string,{section:string;original:string}>;
function fresh(value:any):any{if(Array.isArray(value))return value.map(fresh);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,k==='id'||k==='slug'?'new-'+crypto.randomUUID().slice(0,8):k==='width'||k==='height'?1000:typeof v==='boolean'?false:typeof v==='string'?'':fresh(v)]));return typeof value==='number'?0:typeof value==='boolean'?false:'';}
function Field({value,onChange,name,media,path}:{value:any;onChange:(v:any)=>void;name:string;media:Media[];path:string}){
 const label=labels[name]||name;
 if(Array.isArray(value))return <div className="cms-array"><h4>{label}</h4>{value.map((item,i)=><div className="cms-array-row" key={i}><Field value={item} onChange={v=>onChange(value.map((x,n)=>n===i?v:x))} name={`${label} ${i+1}`} media={media} path={`${path}.${i}`}/><button type="button" aria-label={`حذف ${label} ${i+1}`} onClick={()=>onChange(value.filter((_,n)=>n!==i))}>حذف</button></div>)}<button type="button" onClick={()=>onChange([...value,value.length?fresh(value[0]):''])}>＋ افزودن مورد</button></div>;
 if(value&&typeof value==='object')return <div className="cms-field-grid">{Object.entries(value).map(([k,v])=><Field key={k} value={v} onChange={next=>onChange({...value,[k]:next})} name={k} media={media} path={`${path}.${k}`}/>)}</div>;
 if(typeof value==='boolean')return <label className="cms-check"><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/>{label}</label>;
 if(mediaKeys.includes(name))return <label className="cms-field">{label}<select value={value||''} onChange={e=>onChange(e.target.value)}><option value="">بدون تصویر</option>{!media.some(m=>m.path===value)&&value&&<option value={value}>{value}</option>}{media.map(m=><option key={m.path} value={m.path}>{m.path.split('/').pop()}</option>)}</select><input aria-label={`نشانی ${label}`} dir="ltr" value={value||''} onChange={e=>onChange(e.target.value)} placeholder="/images/example.webp"/>{value&&<img className="cms-image-preview" src={media.find(m=>m.path===value)?.url||assetPath(value)} alt={label}/>}</label>;
 return <label className="cms-field">{label}{typeof value==='number'?<input type="number" min={0} value={value} onChange={e=>onChange(Number(e.target.value))}/>:<textarea rows={String(value).length>100?4:2} dir={/^(https:|\/images|tel:)/.test(value)?'ltr':'auto'} value={value??''} onChange={e=>onChange(e.target.value)}/>}</label>;
}
export function AdminPanel(){
 const [api,setApi]=useState(''),[token,setToken]=useState(''),[data,setData]=useState<Data|null>(null),[sha,setSha]=useState(''),[media,setMedia]=useState<Media[]>([]),[staged,setStaged]=useState<Media[]>([]),[deletes,setDeletes]=useState<string[]>([]),[section,setSection]=useState('site'),[search,setSearch]=useState(''),[group,setGroup]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[dirty,setDirty]=useState(false),[publication,setPublication]=useState<{sha:string;url:string;state:string}|null>(null);
 const publishDialog=useRef<HTMLDialogElement>(null), deleteDialog=useRef<HTMLDialogElement>(null),[toDelete,setToDelete]=useState<{section:string;index:number}|null>(null);
 useEffect(()=>{fetch(assetPath('/admin-config.json')!,{cache:'no-store'}).then(r=>r.json()).then(c=>{if(typeof c.apiBase!=='string'||!c.apiBase){setError('اتصال سرور مدیریت هنوز فعال نشده است.');return;}const u=new URL(c.apiBase);if(u.protocol!=='https:'&&u.hostname!=='127.0.0.1')throw new Error();setApi(u.origin);}).catch(()=>setError('تنظیمات اتصال پنل در دسترس نیست.'));},[]);
 useEffect(()=>{if(!dirty)return;const stop=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',stop);return()=>window.removeEventListener('beforeunload',stop);},[dirty]);
 async function call(path:string,body?:unknown,auth=token){const r=await fetch(api+path,{method:body?'POST':'GET',headers:{...(auth?{Authorization:'Bearer '+auth}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const result=await r.json();if(!r.ok){if(r.status===401&&path!=='/login'){setToken('');}throw new Error(result.error||'ارتباط با سرور انجام نشد.');}return result;}
 async function load(auth=token){const result=await call('/content',undefined,auth);setData(result.content);setSha(result.sha);setMedia(result.media);setStaged([]);setDeletes([]);setDirty(false);}
 async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{const r=await call('/login',{username:f.get('username'),password:f.get('password')},'');setToken(r.token);if(data&&dirty)setNotice('دوباره وارد شدید؛ پیش‌نویس شما حفظ شده است.');else await load(r.token);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function update(next:Data){setData(next);setDirty(true);setNotice('');}
 async function publish(){if(!data)return;setBusy(true);setError('');try{validateContent(data);const r=await call('/publish',{sha,content:data,assets:staged.map(({path,base64})=>({path,base64})),deletes});setPublication({...r,state:'تغییرات در گیت‌هاب ثبت شد؛ ساخت سایت در انتظار اجراست.'});publishDialog.current?.close();await load();setNotice('تغییرات ثبت شد. انتشار عمومی پس از موفقیت ساخت انجام می‌شود.');}catch(e){publishDialog.current?.close();setError((e as Error).message);}finally{setBusy(false);}}
 async function status(){if(!publication)return;setBusy(true);try{const r=await call('/status?sha='+publication.sha);setPublication({...publication,state:r.conclusion==='success'?'نسخهٔ جدید با موفقیت منتشر شد.':r.conclusion?'ساخت موفق نبود؛ گزارش را بررسی کنید.':r.status==='queued'?'ساخت در صف انتظار است.':'ساخت در حال اجراست.'});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function upload(file:File){setBusy(true);setError('');try{if(staged.length>=3)throw new Error('ابتدا این سه تصویر را منتشر کنید و سپس تصویر بعدی را اضافه کنید.');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15*1024*1024)throw new Error('تصویر JPG، PNG یا WebP تا ۱۵ مگابایت انتخاب کنید.');const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>80000000){bitmap.close();throw new Error('ابعاد تصویر بیش از حد بزرگ است.');}const scale=Math.min(1,2400/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('آماده‌سازی تصویر انجام نشد.')),'image/webp',.88));if(blob.type!=='image/webp'||blob.size>2*1024*1024)throw new Error('حجم خروجی تصویر باید کمتر از دو مگابایت باشد.');const base64=await new Promise<string>(resolve=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.readAsDataURL(blob);});const path='/images/cms-'+crypto.randomUUID()+'.webp';setStaged(a=>[...a,{path,url:'data:image/webp;base64,'+base64,base64,width:canvas.width,height:canvas.height}]);setDirty(true);setNotice('تصویر آماده شد؛ در فیلد تصویر بخش دلخواه انتخابش کنید و سپس منتشر کنید.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function backup(){if(!data)return;const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='portfolio-content.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const allMedia=[...staged,...media].filter(m=>!deletes.includes(m.path));
 const editArray=(index:number,value:any)=>update({...data,[section]:data![section].map((v:any,i:number)=>i===index?value:v)});
 if(!token||!data)return <section className="cms-login"><div className="cms-brand">احسان احترامی <span>مدیریت محتوا</span></div><h1>ورود به پنل مدیریت</h1><p>فضای خصوصی برای مدیریت روایت، تصاویر و محتوای سایت.</p><form onSubmit={login}><label>نام کاربری<input name="username" autoComplete="username" dir="ltr" required maxLength={100}/></label><label>رمز عبور<input name="password" type="password" autoComplete="current-password" dir="ltr" required maxLength={200}/></label><button disabled={!api||busy} type="submit">{busy?'در حال ورود…':'ورود به مدیریت'}</button></form>{data&&dirty&&<button type="button" onClick={backup}>دریافت پشتیبان پیش‌نویس حفظ‌شده</button>}{error&&<p role="alert" className="cms-error">{error}</p>}</section>;
 return <section className="cms-app"><header className="cms-top"><div><span className="cms-eyebrow">فضای مدیریت</span><h1>احسان احترامی</h1></div><div className="cms-actions"><span>{dirty?'تغییرات منتشرنشده دارید':'همگام با مخزن'}</span><a href={assetPath('/')} target="_blank" rel="noreferrer">مشاهدهٔ سایت ↗</a><button disabled={busy} onClick={async()=>{if(dirty){setError('پیش از خروج، تغییرات را منتشر یا فایل پشتیبان دریافت کنید. برای صرف‌نظر، صفحه را بازآوری کنید.');return;}try{await call('/logout',{});}finally{setToken('');setData(null);}}}>خروج</button><button className="cms-primary" disabled={busy||!dirty} onClick={()=>{try{validateContent(data);publishDialog.current?.showModal();}catch(e){setError((e as Error).message);}}}>بررسی و انتشار</button></div></header><div className="cms-layout"><aside className="cms-sidebar"><nav aria-label="بخش‌های مدیریت">{Object.entries(sections).map(([key,label])=><button key={key} aria-current={section===key?'page':undefined} onClick={()=>{setSection(key);setSearch('');setGroup('');}}>{label}<span>←</span></button>)}</nav><button onClick={backup}>دریافت پشتیبان محتوا ↓</button><label className="cms-import">بازیابی پشتیبان<input type="file" accept="application/json" onChange={async e=>{try{const file=e.target.files?.[0];if(!file)return;if(file.size>1024*1024)throw new Error('فایل بیش از حد بزرگ است.');update(validateContent(JSON.parse(await file.text())));setNotice('پشتیبان در پیش‌نویس قرار گرفت؛ برای اعمال عمومی منتشر کنید.');}catch(e){setError((e as Error).message);}}}/></label><p>رمز و نشست در مرورگر ذخیره نمی‌شوند. با بازآوری صفحه، ورود مجدد لازم است.</p></aside><div className="cms-main" aria-busy={busy}>{error&&<div role="alert" className="cms-error">{error}<button onClick={()=>setError('')}>بستن</button></div>}{notice&&<p role="status" className="cms-notice">{notice}</p>}{publication&&<div className="cms-publication"><p>{publication.state}</p><button disabled={busy} onClick={status}>بررسی وضعیت انتشار</button><a href={publication.url} target="_blank" rel="noreferrer">تاریخچهٔ تغییرات ↗</a></div>}<div className="cms-section-heading"><div><span className="cms-eyebrow">محتوای وب‌سایت</span><h2>{sections[section]}</h2></div><button disabled={busy||dirty} onClick={()=>{setBusy(true);load().catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>دریافت آخرین نسخه</button></div>
 {section==='media'?<><label className="cms-upload">＋ افزودن تصویر<input type="file" disabled={busy} accept="image/jpeg,image/png,image/webp" onChange={e=>{if(e.target.files?.[0])upload(e.target.files[0]);e.target.value='';}}/><small>تصویر به WebP تبدیل می‌شود؛ سه تصویر در هر انتشار.</small></label><div className="cms-media-grid">{allMedia.map(m=>{const used=JSON.stringify(data).includes(m.path);return <article key={m.path}><img src={m.url} alt={m.path.split('/').pop()} loading="lazy"/><code>{m.path}</code><small>{used?'در حال استفاده':'بدون استفاده'}{m.width?` · ${m.width} × ${m.height}`:''}</small><button disabled={used||busy} onClick={()=>{if(staged.some(x=>x.path===m.path))setStaged(a=>a.filter(x=>x.path!==m.path));else setDeletes(a=>[...a,m.path]);setDirty(true);}}>حذف در انتشار بعدی</button></article>;})}</div>{deletes.length>0&&<button onClick={()=>setDeletes([])}>بازگرداندن حذف تصاویر ({deletes.length})</button>}</>:
 section==='copy'||section==='links'?<><div className="cms-search"><label>جست‌وجوی متن<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="عنوان یا بخشی از متن…"/></label><label>صفحه یا بخش<select value={group} onChange={e=>setGroup(e.target.value)}><option value="">همهٔ بخش‌ها</option>{[...new Set(Object.keys(data[section]).map(k=>fieldMeta[k]?.section))].filter(Boolean).map(g=><option key={g} value={g}>{g}</option>)}</select></label></div><div className="cms-copy-fields">{Object.entries(data[section] as Record<string,string>).filter(([k,v])=>(!group||fieldMeta[k]?.section===group)&&(!search||(v+fieldMeta[k]?.original).includes(search))).map(([k,v])=><label key={k}><small>{fieldMeta[k]?.section}</small><span>{fieldMeta[k]?.original.slice(0,90)}</span><textarea dir="auto" value={v} rows={v.length>100?4:2} onChange={e=>update({...data,[section]:{...data[section],[k]:e.target.value}})}/></label>)}</div></>:
 Array.isArray(data[section])?<><div className="cms-collection-tools"><span>{data[section].length.toLocaleString('fa-IR')} مورد</span><button onClick={()=>{const sample=(defaults as Data)[section]?.[0]||(section==='testimonials'?{name:'',role:'',text:''}:'');let item=fresh(sample);if(section==='works')item={...item,category:data.categories[1]||data.categories[0],featured:false,video:'',before:'',after:''};update({...data,[section]:[...data[section],item]});}}>＋ افزودن {sections[section]}</button></div>{data[section].map((item:any,i:number)=><details className="cms-item" key={i}><summary><span>{(i+1).toLocaleString('fa-IR')}</span>{typeof item==='string'?item||'مورد جدید':Array.isArray(item)?item[1]||'پیوند جدید':item.title||item.name||item.q||'مورد جدید'}</summary><div className="cms-item-body"><Field name={sections[section]} path={`${section}.${i}`} value={section==='works'?{featured:false,video:'',before:'',after:'',...item}:item} onChange={v=>editArray(i,v)} media={allMedia}/><div className="cms-item-tools"><button disabled={i===0} onClick={()=>{const a=[...data[section]];[a[i-1],a[i]]=[a[i],a[i-1]];update({...data,[section]:a});}}>↑ جابه‌جایی به بالا</button><button disabled={i===data[section].length-1} onClick={()=>{const a=[...data[section]];[a[i+1],a[i]]=[a[i],a[i+1]];update({...data,[section]:a});}}>↓ جابه‌جایی به پایین</button><button className="cms-danger" onClick={()=>{setToDelete({section,index:i});deleteDialog.current?.showModal();}}>حذف مورد</button></div></div></details>)}</>:<Field name={sections[section]} value={data[section]} onChange={v=>update({...data,[section]:v})} path={section} media={allMedia}/>}
 </div></div><dialog className="cms-dialog" ref={publishDialog}><h2>انتشار تغییرات</h2><p>متن‌ها و تصاویر پیش‌نویس در مخزن گیت‌هاب ثبت و پس از ساخت موفق، عمومی می‌شوند.</p><p>{staged.length.toLocaleString('fa-IR')} تصویر جدید · {deletes.length.toLocaleString('fa-IR')} تصویر برای حذف</p><div className="cms-actions"><button disabled={busy} onClick={()=>publishDialog.current?.close()}>بازگشت به ویرایش</button><button className="cms-primary" disabled={busy} onClick={publish}>{busy?'در حال ثبت…':'ثبت و انتشار تغییرات'}</button></div></dialog><dialog ref={deleteDialog} className="cms-dialog"><h2>حذف این مورد؟</h2><p>این تغییر تا پیش از انتشار فقط در پیش‌نویس شما اعمال می‌شود.</p><button onClick={()=>deleteDialog.current?.close()}>انصراف</button><button className="cms-danger" onClick={()=>{if(toDelete)update({...data,[toDelete.section]:data[toDelete.section].filter((_:any,i:number)=>i!==toDelete.index)});deleteDialog.current?.close();}}>حذف از پیش‌نویس</button></dialog></section>;
}
